name: Code Quality and Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: stock_markets
          channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          conda install pylint
      - name: Code Review Scoring
        run: |
          conda activate stock_markets
          find . -name '*.py' -exec pylint {} \;
        shell: bash -l {0}
      - name: List Python files
        run: |
          find . -name '*.py'
        shell: /usr/bin/bash -l {0}
      - name: Run PyLint
        run: |
          FILES=$(find . -name '*.py')
          if [ -z "$FILES" ]; then
            echo "No Python files to lint."
          else
            pylint $FILES --fail-under=8.0
          fi
        shell: /usr/bin/bash -l {0}
      - name: Run Tests and Generate Coverage Report
        run: |
          pip install coverage pytest-cov
          coverage run -m pytest
          coverage report
          coverage xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
