name: Pylint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: stock_markets
          channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          conda install pylint
      - name: Code Review Scoring
        run: |
          conda activate stock_markets
          find . -name '*.py' -exec pylint {} \;
        shell: bash -l {0}
      - name: Run PyLint
        run: |
          conda activate stock_markets
          pylint $(find . -name '*.py') --fail-under=8.0
        shell: bash -l {0}
